# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Auth-Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Auth-Practice
  pod 'Then'
  pod 'Moya', '~> 15.0'
  pod 'SwiftGen', '~> 6.0'
  pod 'SnapKit', '~> 5.0.0'

end
